CREATE TABLE USUA (
    USUA_CD_ID SERIAL PRIMARY KEY,
    USUA_TX_NOME VARCHAR(255) NOT NULL,
    USUA_TX_NOMESOCIAL VARCHAR(255),
    USUA_TX_EMAIL VARCHAR(255) NOT NULL UNIQUE,
    USUA_TX_TELEFONE VARCHAR(255),
    USUA_TX_SENHA VARCHAR(255) NOT NULL,
    USUA_TX_SEGREDO VARCHAR(255),
    USUA_BL_TWOFACTOR BOOLEAN NOT NULL,
    USUA_DT_NASCIMENTO DATE,
    USUA_TX_TIPO VARCHAR(255) NOT NULL,
    USUA_TX_STATUS VARCHAR(255) NOT NULL,
    USUA_DT_CADASTRO TIMESTAMP NOT NULL,
    USUA_DT_ATUALIZACAO TIMESTAMP NOT NULL
);

CREATE TABLE FOTO (
    FOTO_CD_ID SERIAL PRIMARY KEY,
    FOTO_TX_NOME VARCHAR(255) NOT NULL,
    FOTO_TX_DESCRICAO VARCHAR(255) NOT NULL,
    FOTO_TX_URL VARCHAR(255) NOT NULL,
    FOTO_TX_CONTENTTYPE VARCHAR(255) NOT NULL,
    FOTO_TX_TAMANHO BIGINT NOT NULL,
    PK_USUA BIGINT NOT NULL,
    CONSTRAINT FK_USUA_FOTO FOREIGN KEY (PK_USUA) REFERENCES USUA (USUA_CD_ID)
);

CREATE TABLE CONT (
    CONT_CD_ID SERIAL PRIMARY KEY,
    CONT_TX_NOME VARCHAR(255) NOT NULL,
    CONT_TX_TIPO VARCHAR(255) NOT NULL,
    CONT_TX_URL VARCHAR(255) NOT NULL,
    CONT_BL_PRIVADO BOOLEAN NOT NULL,
    PK_USUA BIGINT NOT NULL,
    CONSTRAINT FK_USUA_CONT FOREIGN KEY (PK_USUA) REFERENCES USUA (USUA_CD_ID)
);