CREATE TABLE CART (
    CART_CD_ID SERIAL PRIMARY KEY,
    CART_TX_NOMECARTAO VARCHAR(255) NOT NULL,
    CART_TX_NOMEUSUARIO VARCHAR(255) NOT NULL,
    CART_TX_USUARIOTIPO VARCHAR(255),
    CART_TX_BACKGROUND VARCHAR(255),
    CART_TX_URL VARCHAR(255),
    CART_TX_QRCODE VARCHAR(255) NOT NULL,
    CART_BL_ATIVO BOOLEAN NOT NULL,
    CART_DT_CADASTRO TIMESTAMP NOT NULL,
    CART_DT_ATUALIZACAO TIMESTAMP NOT NULL,
    PK_USUA BIGINT NOT NULL,
    CONSTRAINT FK_USUA_CART FOREIGN KEY (PK_USUA) REFERENCES USUA (USUA_CD_ID)
);